### ISSUE TITLE
[BE] Milestone API 기능 구현

### ISSUE THREAD

**Issue by hsik0225** [codesquad-member-2020/issue-tracker-08#58]
### Milestone API 기능 구현

- [x] /milestones GET
- [x] /milestones POST
- [x] /milestones/{milestone_id} PUT
- [x] /milestones/{milestone_id} PATCH
- [x] /milestones/{milestone_id} DELETE

**Comment by beginin15** [comment]
## 리팩토링
- `milestone.setId()` 으로 직접하지 말고 `Milestone.of()`로 세팅하도록 변경
